FROM python:3.9-slim

WORKDIR /app

COPY pyproject.toml poetry.lock ./

RUN pip install poetry \
    && poetry config virtualenvs.create false \
    && poetry install --without dev --no-interaction --no-ansi --no-root \
    && useradd --no-log-init --create-home --shell /bin/bash appuser \
    && chown -R appuser:appuser /app

USER appuser

COPY . .

ENV PYTHONPATH=/app/src

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "laf.app:app"]
